If old dark exists, this is now renamed before the new one is created. fits_median return code is error checked.

diff --git a/scripts/autoguider_make_dark b/scripts/autoguider_make_dark
--- a/scripts/autoguider_make_dark
+++ b/scripts/autoguider_make_dark
@@ -1,5 +1,5 @@
 #!/bin/csh
-# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_make_dark,v 1.4 2006-05-22 17:24:00 cjm Exp $
+# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_make_dark,v 1.5 2006-06-19 15:59:21 cjm Exp $
 set gaiadisp = 0
 set exposure_length = "1000"
 set exposure_count = "3"
@@ -103,7 +103,6 @@ set file_number = 0
 set done = 0
 set median_command_arguments = "-o ${output_filename}"
 while ( "${done}" == 0 )
-	set date_string = `/bin/date +"%Y-%m-%dT%H:%M:%S"`
 	set filename = "${output_leaf}_${file_number}.fits"
 	set expose_output = `send_command -h ${hostname} -p ${port} -c "expose ${exposure_length}"`
 	echo "expose ${exposure_length} returned : ${expose_output}"
@@ -112,6 +111,7 @@ while ( "${done}" == 0 )
 		echo "expose ${exposure_length} failed (${retval})."
 		exit 1
 	endif
+	# NB getfits_command overwrites any previously existing filename of this name.
 	getfits_command -h ${hostname} -p ${port} -c "getfits field raw" -f ${filename}
 	set retval = $status
 	if( "${retval}" != "0" ) then
@@ -127,9 +127,30 @@ while ( "${done}" == 0 )
 	    set done = 1
 	endif
 end
+#
+# If the median/output file already exists, the fits_median call will fail.
+# Detect existence of output filename and rename appropriately.
+#
+if ( -e "${output_filename}" ) then
+    echo "${output_filename} already exists, trying to rename old file... "
+    set date_string = `/bin/date +"%Y-%m-%dT%H:%M:%S"`
+    set old_output_filename = "${output_filename}.old.${date_string}"
+    echo "/bin/mv ${output_filename} ${old_output_filename}"
+    /bin/mv ${output_filename} ${old_output_filename}
+    set retval = $status
+    if( "${retval}" != "0" ) then
+	echo "/bin/mv ${output_filename} ${old_output_filename} failed (${retval})."
+	exit 1
+    endif
+endif
 echo "About to create median."
 echo "fits_median ${median_command_arguments}"
 fits_median ${median_command_arguments}
+set retval = $status
+if( "${retval}" != "0" ) then
+    echo "fits_median failed (${retval})."
+    exit 1
+endif
 echo "Dark median ${output_filename} created."
 if( "${gaiadisp}" == "1" ) then
     gaiadisp ${output_filename}
@@ -139,6 +160,9 @@ echo "Note, field flat-fielding is now turned off, use:send_command -h ${hostnam
 echo "Note, field object detection is now turned off, use:send_command -h ${hostname} -p ${port} -c'field object on' to restore."
 #
 # $Log: not supported by cvs2svn $
+# Revision 1.4  2006/05/22 17:24:00  cjm
+# Added extra echos at end.
+#
 # Revision 1.3  2006/05/22 17:20:07  cjm
 # Added error checking, and turning off of reductions.
 #
