Added -delete option to delete frames after displaying them.

diff --git a/scripts/autoguider_get_guide_frames b/scripts/autoguider_get_guide_frames
--- a/scripts/autoguider_get_guide_frames
+++ b/scripts/autoguider_get_guide_frames
@@ -1,35 +1,56 @@
 #!/bin/csh
-# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_get_guide_frames,v 1.2 2006-04-13 15:54:08 cjm Exp $
+# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_get_guide_frames,v 1.3 2006-05-10 15:45:14 cjm Exp $
 set gaiadisp = 0
-if ( $#args == 1 ) then
-	if( $1 == "-gaiadisp" ) then
+set delete_frames = 0
+set frame_type_string = "raw"
+if ( $#argv > 0 ) then
+    foreach arg ( $argv )
+	if( "$arg" == "-delete" ) then
+		set delete_frames = 1
+	else if( "$arg" == "-gaiadisp" ) then
 		set gaiadisp = 1
-	else if( $1 == "-help" ) then
-		echo "autoguider_get_guide_frames [-gaiadisp]"
+	else if( "$arg" == "-raw" ) then
+		set frame_type_string = "raw"
+	else if( "$arg" == "-reduced" ) then
+		set frame_type_string = "reduced"
+	else if( "$arg" == "-help" ) then
+		echo "autoguider_get_guide_frames [-gaiadisp][-raw|-reduced][-delete]"
 		exit 1
 	else 
 		echo "Unknown argument: $1"
 		exit 1
-else
-	echo "autoguider_get_guide_frames [-gaiadisp]"
-	exit 1
+        endif
+    end
 endif
-alias getfits_command "/icc/bin/autoguider/commandserver/test/i386-linux/test_getfits_command"
+if ( -r /home/dev/bin/autoguider/commandserver/test/i386-linux/test_getfits_command ) then
+    alias getfits_command "/home/dev/bin/autoguider/commandserver/test/i386-linux/test_getfits_command"
+else if ( -r /icc/bin/autoguider/commandserver/test/i386-linux/test_getfits_command ) then
+    alias getfits_command "/icc/bin/autoguider/commandserver/test/i386-linux/test_getfits_command"
+else
+    echo "Could not find test_getfits_command."
+    exit 2
+endif
 set hostname = "autoguider1"
-set port = "1234"
+set port = "6571"
 set file_number = 0
 set done = 0
 while ( "${done}" == 0 )
 	set date_string = `/bin/date +"%Y-%m-%dT%H:%M:%S"`
-	set filename = "guide_${date_string}_${file_number}.fits"
-	getfits_command -h ${hostname} -p ${port} -c "getfits guide" -f guide_${date_string}_${file_number}.fits
+	set filename = "guide_${frame_type_string}_${date_string}_${file_number}.fits"
+	getfits_command -h ${hostname} -p ${port} -c "getfits guide ${frame_type_string}" -f ${filename}
 	@ file_number ++
-	if( ${gaiadisp} == 1 ) then
+	if( "${gaiadisp}" == "1" ) then
 		gaiadisp ${filename}
+	endif
+	if( "${delete_frames}" == "1" ) then
+	    /bin/rm ${filename}
 	endif
 end
 #
 # $Log: not supported by cvs2svn $
+# Revision 1.2  2006/04/13 15:54:08  cjm
+# Added gaiadisp args.
+#
 # Revision 1.1  2006/04/13 15:25:07  cjm
 # Initial revision
 #
