Changes relating to deploying the IUCAA autoguider code.

diff --git a/scripts/autoguider_make_deployment b/scripts/autoguider_make_deployment
--- a/scripts/autoguider_make_deployment
+++ b/scripts/autoguider_make_deployment
@@ -1,6 +1,6 @@
 #!/bin/csh
-# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_make_deployment,v 1.21 2013-11-27 14:53:26 cjm Exp $
-# Version: $Revision: 1.21 $
+# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_make_deployment,v 1.22 2014-01-31 17:36:28 cjm Exp $
+# Version: $Revision: 1.22 $
 # By $Author: cjm $
 # Make a deployment tar file.
 # This contains:
@@ -21,7 +21,17 @@ if ( "${machine_name}" == "-help") then
 	exit 0
 endif
 set camera_name = "autoguider"
-
+switch ( "${machine_name}" )
+    case "autoguider1":
+	set camera_library = "libautoguider_ccd_andor.so"
+	breaksw
+    case "iucaaag":
+	set camera_library = "libautoguider_ccd_fli.so"
+	breaksw
+    default:
+	echo "Unknown camera for machine ${machine_name}. Deployment creation failed."
+	exit 1
+endsw
 # dev root directory
 set dev_dir 		= "~dev"
 # dev binary root directory
@@ -70,7 +80,18 @@ endif
 #
 echo "Creating directory structure..."
 set dir_count = 0
-set dir_list = "${deployment_dir} ${deployment_dir}/${init_d_dir} ${deployment_icc_dir} ${deployment_bin_dir} ${deployment_dir}/icc/tmp ${deployment_dir}/icc/tmp/log_archive ${deployment_dir}/icc/log ${deployment_icc_dir}/config ${deployment_icc_dir}/dprt/dark ${deployment_icc_dir}/dprt/flat ${deployment_bin_dir}/scripts ${deployment_bin_dir}/autoguider/scripts ${deployment_bin_dir}/autoguider/c/${HOSTTYPE} ${deployment_bin_dir}/autoguider/commandserver/test/${HOSTTYPE} ${deployment_bin_dir}/autoguider/ccd/andor/test/${HOSTTYPE} ${deployment_bin_dir}/andor/examples/console/cooling ${deployment_bin_dir}/andor/examples/console/image ${deployment_bin_dir}/autoguider/ngatcil/test/${HOSTTYPE} ${deployment_bin_dir}/ics_util/c/${HOSTTYPE} ${deployment_bin_dir}/iboot/${HOSTTYPE} ${deployment_bin_dir}/ccd/misc/${HOSTTYPE} ${deployment_bin_dir}/javalib ${deployment_bin_dir}/lib/${HOSTTYPE} ${deployment_bin_dir}/autoguider/test ${deployment_bin_dir}/libdprt/object/test/${HOSTTYPE} ${deployment_bin_dir}/log_udp/test/${HOSTTYPE} ${deployment_bin_dir}/autobooter/java ${deployment_bin_dir}/autoguider/java/gui"
+set dir_list = "${deployment_dir} ${deployment_dir}/${init_d_dir} ${deployment_icc_dir} ${deployment_bin_dir} ${deployment_dir}/icc/tmp ${deployment_dir}/icc/tmp/log_archive ${deployment_dir}/icc/log ${deployment_icc_dir}/config ${deployment_icc_dir}/dprt/dark ${deployment_icc_dir}/dprt/flat ${deployment_bin_dir}/scripts ${deployment_bin_dir}/autoguider/scripts ${deployment_bin_dir}/autoguider/c/${HOSTTYPE} ${deployment_bin_dir}/autoguider/commandserver/test/${HOSTTYPE} ${deployment_bin_dir}/autoguider/ngatcil/test/${HOSTTYPE} ${deployment_bin_dir}/ics_util/c/${HOSTTYPE} ${deployment_bin_dir}/iboot/${HOSTTYPE} ${deployment_bin_dir}/ccd/misc/${HOSTTYPE} ${deployment_bin_dir}/javalib ${deployment_bin_dir}/lib/${HOSTTYPE} ${deployment_bin_dir}/autoguider/test ${deployment_bin_dir}/libdprt/object/test/${HOSTTYPE} ${deployment_bin_dir}/log_udp/test/${HOSTTYPE} ${deployment_bin_dir}/autobooter/java ${deployment_bin_dir}/autoguider/java/gui"
+switch ( "${machine_name}" )
+    case "autoguider1":
+	set dir_list = "${dir_list} ${deployment_bin_dir}/autoguider/ccd/andor/test/${HOSTTYPE} ${deployment_bin_dir}/andor/examples/console/cooling ${deployment_bin_dir}/andor/examples/console/image"
+	breaksw
+    case "iucaaag":
+	set dir_list = "${dir_list} ${deployment_bin_dir}/autoguider/ccd/fli/test/${HOSTTYPE}"
+	breaksw
+    default:
+	echo "Unknown machine ${machine_name}. Deployment creation failed."
+	exit 1
+endsw
 # ${deployment_bin_dir}/autoguider/andor/examples/common  
 foreach dir ( ${dir_list} )
 	mkdir -p ${dir}
@@ -168,7 +189,7 @@ echo "${java_class_dir_count} Java class directories copied with ${java_class_fi
 # C libraries
 #
 echo "Copying C libraries..."
-set clib_list = "libcfitsio.so libdprt_object.so libdprt_libfits.so libccd_dprt.so liblt_filenames.so libngatastro.so libautoguider_commandserver.so libautoguider_ccd_general.so libautoguider_ccd_andor.so libautoguider_ngatcil.so libestar_config.so liblog_udp.so"
+set clib_list = "libcfitsio.so libdprt_object.so libdprt_libfits.so libccd_dprt.so liblt_filenames.so libngatastro.so libautoguider_commandserver.so libautoguider_ccd_general.so ${camera_library} libautoguider_ngatcil.so libestar_config.so liblog_udp.so"
 set clib_count = 0
 foreach clib ( ${clib_list} )
 	echo "C Library : ${clib}"
@@ -206,7 +227,18 @@ echo "${clib_count} C libraries copied."
 # C programs
 #
 echo "Copying C program directories..."
-set dir_list = "autoguider/c/${HOSTTYPE} autoguider/commandserver/test/${HOSTTYPE} autoguider/ngatcil/test/${HOSTTYPE} autoguider/ccd/andor/test/${HOSTTYPE} andor/examples/console/cooling andor/examples/console/image ics_util/c/${HOSTTYPE} iboot/${HOSTTYPE} ccd/misc/${HOSTTYPE} libdprt/object/test/${HOSTTYPE} log_udp/test/${HOSTTYPE}"
+set dir_list = "autoguider/c/${HOSTTYPE} autoguider/commandserver/test/${HOSTTYPE} autoguider/ngatcil/test/${HOSTTYPE} ics_util/c/${HOSTTYPE} iboot/${HOSTTYPE} ccd/misc/${HOSTTYPE} libdprt/object/test/${HOSTTYPE} log_udp/test/${HOSTTYPE}"
+switch ( "${machine_name}" )
+    case "autoguider1":
+	set dir_list = "${dir_list} autoguider/ccd/andor/test/${HOSTTYPE} andor/examples/console/cooling andor/examples/console/image"
+	breaksw
+    case "iucaaag":
+	set dir_list = "${dir_list} autoguider/ccd/fli/test/${HOSTTYPE}"
+	breaksw
+    default:
+	echo "Unknown machine ${machine_name}. Deployment creation failed."
+	exit 1
+endsw
 set dir_count = 0
 set file_count = 0
 # clean out deployment_tmp_dir
@@ -257,8 +289,8 @@ echo "${dir_count} C test program directories copied, containg ${file_count} C t
 # Scripts
 #
 echo "Copying scripts..."
-set file_list = "bin/scripts/configure_tai_data.csh bin/scripts/delete_log_files.csh bin/scripts/killhup.csh bin/scripts/fuser_check bin/autoguider/scripts/autoguider_field bin/autoguider/scripts/autoguider_get_exposure_lengths bin/autoguider/scripts/autoguider_get_guide_frames bin/autoguider/scripts/autoguider_get_guide_frames_cron bin/autoguider/scripts/autoguider_get_guide_packets bin/autoguider/scripts/autoguider_get_guide_packets_with_time bin/autoguider/scripts/autoguider_get_object_list bin/autoguider/scripts/autoguider_get_process_stats bin/autoguider/scripts/autoguider_guide bin/autoguider/scripts/autoguider_guide_packets_graph bin/autoguider/scripts/autoguider_guide_packets_to_csv bin/autoguider/scripts/autoguider_make_dark bin/autoguider/scripts/autoguider_make_dark_list bin/autoguider/scripts/autoguider_make_flat bin/autoguider/scripts/autoguider_object_list_graph bin/autoguider/scripts/autoguider_object_list_to_csv bin/autoguider/scripts/autoguider_rm_guide_frames_cron bin/autoguider/scripts/autoguider_rm_field_frames_cron bin/autoguider/scripts/csv2gnuplot.sh bin/autoguider/scripts/print_line.awk bin/autoguider/java/gui/arse bin/autoguider/scripts/autoguider_temperature_to_csv bin/autoguider/scripts/autoguider_log_get_temperature"
-#bin/scripts/autoguider_reboot bin/scripts/autoguider_engineering_mode bin/scripts/${HOSTTYPE}.random.awk bin/ccs_gui/java/icsgui bin/scripts/dprt_reduce_data
+set file_list = "bin/scripts/configure_tai_data.csh bin/scripts/delete_log_files.csh bin/scripts/killhup.csh bin/scripts/fuser_check bin/autoguider/scripts/autoguider_field bin/autoguider/scripts/autoguider_get_exposure_lengths bin/autoguider/scripts/autoguider_get_guide_frames bin/autoguider/scripts/autoguider_get_guide_frames_cron bin/autoguider/scripts/autoguider_get_guide_packets bin/autoguider/scripts/autoguider_get_guide_packets_with_time bin/autoguider/scripts/autoguider_get_object_list bin/autoguider/scripts/autoguider_get_process_stats bin/autoguider/scripts/autoguider_guide bin/autoguider/scripts/autoguider_guide_packets_graph bin/autoguider/scripts/autoguider_guide_packets_to_csv bin/autoguider/scripts/autoguider_make_dark bin/autoguider/scripts/autoguider_make_dark_list bin/autoguider/scripts/autoguider_make_flat bin/autoguider/scripts/autoguider_object_list_graph bin/autoguider/scripts/autoguider_object_list_graph_column bin/autoguider/scripts/autoguider_object_list_graph_fwhm bin/autoguider/scripts/autoguider_object_list_to_csv bin/autoguider/scripts/autoguider_rm_guide_frames_cron bin/autoguider/scripts/autoguider_rm_field_frames_cron bin/autoguider/scripts/csv2gnuplot.sh bin/autoguider/scripts/print_line.awk bin/autoguider/java/gui/autoguider_runtime_system_evaluator bin/autoguider/scripts/autoguider_temperature_to_csv bin/autoguider/scripts/autoguider_log_get_temperature bin/autoguider/scripts/autoguider_engineering_mode "
+#bin/scripts/autoguider_reboot bin/scripts/${HOSTTYPE}.random.awk bin/ccs_gui/java/icsgui bin/scripts/dprt_reduce_data
 set file_count = 0
 cd ${dev_dir}
 foreach file ( ${file_list} )
@@ -277,7 +309,18 @@ echo "${file_count} scripts copied."
 #
 # in bin sub-directories
 echo "Copying machine configuration files..."
-set file_list = "autoguider/c/${HOSTTYPE}/${machine_name}.autoguider.properties autoguider/ccd/andor/test/${HOSTTYPE}/test_exposure.properties autobooter/java/${machine_name}.autobooter.properties autoguider/java/gui/${machine_name}.ag_gui.properties"
+set file_list = "autoguider/c/${HOSTTYPE}/${machine_name}.autoguider.properties autobooter/java/${machine_name}.autobooter.properties autoguider/java/gui/${machine_name}.ag_gui.properties"
+switch ( "${machine_name}" )
+    case "autoguider1":
+	set file_list = "${file_list} autoguider/ccd/andor/test/${HOSTTYPE}/test_exposure.properties"
+	breaksw
+    case "iucaaag":
+	set file_list = "${file_list}"
+	breaksw
+    default:
+	echo "Unknown machine ${machine_name}. Deployment creation failed."
+	exit 1
+endsw
 set file_count = 0
 cd ${dev_dir}
 foreach file ( ${file_list} )
@@ -390,6 +433,10 @@ echo "Download ${deployment_tar}.gz autoguider_tar_install icc_cshrc icc_cshrc_e
 echo "Deployment ready."
 #
 # $Log: not supported by cvs2svn $
+# Revision 1.21  2013/11/27 14:53:26  cjm
+# autoguider.properties is now a per-machine name config, to allow iucaa support.
+# Added back in libccd_dprt.so from deployment, we seem to need it again.
+#
 # Revision 1.20  2012/03/05 11:33:09  cjm
 # Removed libccd_dprt.so from deployment, we don't seem to need it at the moment,
 # and it does not build.
