Now normalises each flat before medianing, to allow for light level changes during data collection. If old intermediate normalised or medianed files exist, they are deleted. fits_median/fits_normalise error codes checked. If old ouput flat exists it is renamed to .old.${date} before the new one is created.

diff --git a/scripts/autoguider_make_flat b/scripts/autoguider_make_flat
--- a/scripts/autoguider_make_flat
+++ b/scripts/autoguider_make_flat
@@ -1,5 +1,5 @@
 #!/bin/csh
-# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_make_flat,v 1.2 2006-05-22 18:46:34 cjm Exp $
+# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_make_flat,v 1.3 2006-06-19 16:08:06 cjm Exp $
 set gaiadisp = 0
 set exposure_length = "1000"
 set exposure_count = "3"
@@ -134,13 +134,38 @@ while ( "${done}" == 0 )
 	#endif
 	#
 	# get reduced exposure - should be dark subtracted but _not_ flat fielded
+	# NB getfits_command overwrites any previously existing filename of this name.
 	#
 	getfits_command -h ${hostname} -p ${port} -c "getfits field reduced" -f ${filename}
 	@ file_number ++
 	if( "${gaiadisp}" == "1" ) then
 		gaiadisp ${filename}
 	endif
-	set median_command_arguments = " ${median_command_arguments} -i ${filename}"
+	#
+	# Normalise dark-subtracted flat 
+	# This is so we don't always use the middle raw flat when medianing (as sky get darker/brighter)
+	#
+	set normalised_filename = "${output_leaf}_${file_number}_normalised.fits"
+	if( -e "${normalised_filename}" ) then
+	    echo "Old normalised filename exists:/bin/rm ${normalised_filename}"
+	    /bin/rm ${normalised_filename}
+	    set retval = $status
+	    if( "${retval}" != "0" ) then
+		echo "/bin/rm ${normalised_filename} failed (${retval})."
+		exit 1
+	    endif
+	endif
+	echo "fits_normalise -i ${filename} -o ${normalised_filename}"
+	fits_normalise -i ${filename} -o ${normalised_filename}
+	set retval = $status
+	if( "${retval}" != "0" ) then
+	    echo "fits_normalise failed (${retval})."
+	    exit 1
+	endif
+	#
+	# Add normalised image to median command line
+	#
+	set median_command_arguments = " ${median_command_arguments} -i ${normalised_filename}"
 	if( "${file_number}" == "${exposure_count}" ) then
 	    set done = 1
 	endif
@@ -148,18 +173,53 @@ end
 #
 # median reduced dark subtracted filenames
 #
+if( -e "${median_filename}" ) then
+    echo "Old medianed filename exists:/bin/rm ${median_filename}"
+    /bin/rm ${median_filename}
+    set retval = $status
+    if( "${retval}" != "0" ) then
+        echo "/bin/rm ${median_filename} failed (${retval})."
+	exit 1
+    endif
+endif
 echo "About to create median."
 echo "fits_median ${median_command_arguments}"
 fits_median ${median_command_arguments}
+set retval = $status
+if( "${retval}" != "0" ) then
+    echo "fits_median failed (${retval})."
+    exit 1
+endif
 echo "Flat median ${median_filename} created."
 if( "${gaiadisp}" == "1" ) then
     gaiadisp ${median_filename}
 endif
 #
-# Normalise medianed file to create output
+# re-normalise medianed file to create normalised-medianed output
 #
+#
+# If the flat/output file already exists, the fits_normalise call will fail.
+# Detect existence of output filename and rename appropriately.
+#
+if ( -e "${output_filename}" ) then
+    echo "${output_filename} already exists, trying to rename old file... "
+    set date_string = `/bin/date +"%Y-%m-%dT%H:%M:%S"`
+    set old_output_filename = "${output_filename}.old.${date_string}"
+    echo "/bin/mv ${output_filename} ${old_output_filename}"
+    /bin/mv ${output_filename} ${old_output_filename}
+    set retval = $status
+    if( "${retval}" != "0" ) then
+	echo "/bin/mv ${output_filename} ${old_output_filename} failed (${retval})."
+	exit 1
+    endif
+endif
 echo "fits_normalise -i ${median_filename} -o ${output_filename}"
 fits_normalise -i ${median_filename} -o ${output_filename}
+set retval = $status
+if( "${retval}" != "0" ) then
+    echo "fits_normalise failed (${retval})."
+    exit 1
+endif
 echo "Flat normalised median ${output_filename} created."
 if( "${gaiadisp}" == "1" ) then
     gaiadisp ${output_filename}
@@ -168,6 +228,9 @@ echo "Note, field flat-fielding is now turned off, use:send_command -h ${hostnam
 echo "Note, field object detection is now turned off, use:send_command -h ${hostname} -p ${port} -c'field object on' to restore."
 #
 # $Log: not supported by cvs2svn $
+# Revision 1.2  2006/05/22 18:46:34  cjm
+# Bug-fixed so it now works.
+#
 # Revision 1.1  2006/05/22 17:24:16  cjm
 # Initial revision
 #
