Added autobooter deployment.

diff --git a/scripts/autoguider_make_deployment b/scripts/autoguider_make_deployment
--- a/scripts/autoguider_make_deployment
+++ b/scripts/autoguider_make_deployment
@@ -1,6 +1,6 @@
 #!/bin/csh
-# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_make_deployment,v 1.1 2006-06-07 11:10:57 cjm Exp $
-# Version: $Revision: 1.1 $
+# $Header: /home/cjm/cvs/autoguider/scripts/autoguider_make_deployment,v 1.2 2006-07-20 15:39:17 cjm Exp $
+# Version: $Revision: 1.2 $
 # By $Author: cjm $
 # Make a deployment tar file.
 # This contains:
@@ -70,7 +70,7 @@ endif
 #
 echo "Creating directory structure..."
 set dir_count = 0
-set dir_list = "${deployment_dir} ${deployment_dir}/${init_d_dir} ${deployment_icc_dir} ${deployment_bin_dir} ${deployment_dir}/icc/tmp ${deployment_dir}/icc/tmp/log_archive ${deployment_dir}/icc/log ${deployment_icc_dir}/config ${deployment_icc_dir}/dprt/dark ${deployment_icc_dir}/dprt/flat ${deployment_bin_dir}/scripts ${deployment_bin_dir}/autoguider/scripts ${deployment_bin_dir}/autoguider/c/${HOSTTYPE} ${deployment_bin_dir}/autoguider/commandserver/test/${HOSTTYPE} ${deployment_bin_dir}/autoguider/ccd/andor/test/${HOSTTYPE} ${deployment_bin_dir}/autoguider/ngatcil/test/${HOSTTYPE} ${deployment_bin_dir}/autoguider/andor/examples/common ${deployment_bin_dir}/autoguider/andor/examples/console/cooling ${deployment_bin_dir}/autoguider/andor/examples/console/image ${deployment_bin_dir}/ics_util/c/${HOSTTYPE} ${deployment_bin_dir}/ccd/misc/${HOSTTYPE} ${deployment_bin_dir}/javalib ${deployment_bin_dir}/lib/${HOSTTYPE} ${deployment_bin_dir}/autoguider/test ${deployment_bin_dir}/libdprt/object/test/${HOSTTYPE}"
+set dir_list = "${deployment_dir} ${deployment_dir}/${init_d_dir} ${deployment_icc_dir} ${deployment_bin_dir} ${deployment_dir}/icc/tmp ${deployment_dir}/icc/tmp/log_archive ${deployment_dir}/icc/log ${deployment_icc_dir}/config ${deployment_icc_dir}/dprt/dark ${deployment_icc_dir}/dprt/flat ${deployment_bin_dir}/scripts ${deployment_bin_dir}/autoguider/scripts ${deployment_bin_dir}/autoguider/c/${HOSTTYPE} ${deployment_bin_dir}/autoguider/commandserver/test/${HOSTTYPE} ${deployment_bin_dir}/autoguider/ccd/andor/test/${HOSTTYPE} ${deployment_bin_dir}/autoguider/ngatcil/test/${HOSTTYPE} ${deployment_bin_dir}/autoguider/andor/examples/common ${deployment_bin_dir}/autoguider/andor/examples/console/cooling ${deployment_bin_dir}/autoguider/andor/examples/console/image ${deployment_bin_dir}/ics_util/c/${HOSTTYPE} ${deployment_bin_dir}/ccd/misc/${HOSTTYPE} ${deployment_bin_dir}/javalib ${deployment_bin_dir}/lib/${HOSTTYPE} ${deployment_bin_dir}/autoguider/test ${deployment_bin_dir}/libdprt/object/test/${HOSTTYPE} ${deployment_bin_dir}/autobooter/java "
 foreach dir ( ${dir_list} )
 	mkdir -p ${dir}
 	if ($status != 0) then
@@ -92,6 +92,77 @@ if ( "${HOSTTYPE}" == "i386-linux" ) then
        exit 2
     endif
 endif
+#
+# Copy jars
+#
+echo "Copying jars..."
+set jar_list = "ngat_net.jar ngat_util.jar ngat_util_logging.jar"
+set jar_count = 0
+foreach jar ( ${jar_list} )
+	echo "jar : ${jar}"
+# copy jar to deployment location
+	cp ${dev_bin_dir}/javalib/${jar} ${deployment_bin_dir}/javalib
+	set cp_status = $status
+	if( ${cp_status} != 0 ) then
+	    echo "Copy failed: ${dev_bin_dir}/javalib/${jar} to ${deployment_bin_dir}/javalib"
+	    exit 3
+	endif
+# ident contents of jar
+	cd ${deployment_dir}
+	rm -rf ${deployment_tmp_dir}
+	mkdir ${deployment_tmp_dir}
+	cp ${dev_bin_dir}/javalib/${jar} ${deployment_tmp_dir}
+	cd ${deployment_tmp_dir}
+	jar xvf ${jar} > ${deployment_tmp_dir}/jar_output.txt
+	find . -name '*.class' -print > ${deployment_tmp_dir}/class_list.txt
+	foreach class ( `cat ${deployment_tmp_dir}/class_list.txt` )
+		( ident ${class} > ${deployment_tmp_dir}/ident.txt ) >& ${deployment_tmp_dir}/ident_error.txt
+		set ident_string = `cat ${deployment_tmp_dir}/ident.txt`
+		echo "${ident_string}" >>! ${deployment_tmp_dir}/ident_list.txt
+	end
+	if ( -r ${deployment_tmp_dir}/ident_list.txt) then
+		cat ${deployment_tmp_dir}/ident_list.txt >>! ${deployment_icc_dir}/ident_list.txt 
+	endif
+# keep track of number of jars processed
+	@ jar_count ++
+end
+echo "${jar_count} jars copied."
+#
+# Java classes
+#
+echo "Copying Java class directories..."
+set java_class_dir_list = "autobooter/java"
+# grope/java/ngat/grope/ccd/test grope/test 
+set java_class_dir_count = 0
+set java_class_file_count = 0
+foreach java_class_dir ( ${java_class_dir_list} )
+	echo "Java class directory : ${java_class_dir}"
+# copy java_class_dir to deployment location
+	cp ${dev_bin_dir}/${java_class_dir}/*.class ${deployment_bin_dir}/${java_class_dir}
+	set cp_status = $status
+	if( ${cp_status} != 0 ) then
+	    echo "Copy failed: ${dev_bin_dir}/${java_class_dir}/*.class to ${deployment_bin_dir}/${java_class_dir}"
+	    exit 4
+	endif
+# ident each file in dir
+	cd ${deployment_dir}
+	rm -rf ${deployment_tmp_dir}
+	mkdir ${deployment_tmp_dir}
+	cd ${deployment_bin_dir}
+	find ${java_class_dir} -name '*.class' -print > ${deployment_tmp_dir}/class_list.txt
+	foreach class ( `cat ${deployment_tmp_dir}/class_list.txt` )
+		( ident ${class} > ${deployment_tmp_dir}/ident.txt ) >& ${deployment_tmp_dir}/ident_error.txt
+		set ident_string = `cat ${deployment_tmp_dir}/ident.txt`
+		echo "${ident_string}" >>! ${deployment_tmp_dir}/ident_list.txt
+		@ java_class_file_count ++
+	end
+	if ( -r ${deployment_tmp_dir}/ident_list.txt) then
+		cat ${deployment_tmp_dir}/ident_list.txt >>! ${deployment_icc_dir}/ident_list.txt 
+	endif
+# keep track of number of java_class_dirs processed
+	@ java_class_dir_count ++
+end
+echo "${java_class_dir_count} Java class directories copied with ${java_class_file_count} Java classes in them."
 #
 # C libraries
 #
@@ -205,7 +276,7 @@ echo "${file_count} scripts copied."
 #
 # in bin sub-directories
 echo "Copying machine configuration files..."
-set file_list = "autoguider/c/${HOSTTYPE}/autoguider.properties autoguider/ccd/andor/test/${HOSTTYPE}/test_exposure.properties"
+set file_list = "autoguider/c/${HOSTTYPE}/autoguider.properties autoguider/ccd/andor/test/${HOSTTYPE}/test_exposure.properties autobooter/java/${machine_name}.autobooter.properties "
 set file_count = 0
 cd ${dev_dir}
 foreach file ( ${file_list} )
@@ -252,15 +323,15 @@ echo "${file_count} camera configuration files copied."
 #
 # /etc init scripts
 #
-#echo "Copying Autobooter initialisation script."
-#set from_file = "${dev_bin_dir}/autobooter/java/${machine_name}.autobooter"
-#set to_file = "${deployment_dir}/${init_d_dir}/autobooter"
-#cp  ${from_file} ${to_file}
-#set cp_status = $status
-#if( ${cp_status} != 0 ) then
-#    echo "Copy failed: ${from_file} to ${to_file}"
-#    exit 6
-#endif
+echo "Copying Autobooter initialisation script."
+set from_file = "${dev_bin_dir}/autobooter/java/${machine_name}.autobooter"
+set to_file = "${deployment_dir}/${init_d_dir}/autobooter"
+cp  ${from_file} ${to_file}
+set cp_status = $status
+if( ${cp_status} != 0 ) then
+    echo "Copy failed: ${from_file} to ${to_file}"
+    exit 6
+endif
 #
 # Kernel modules
 #
@@ -333,4 +404,7 @@ echo "Download ${deployment_tar}.gz autoguider_tar_install icc_cshrc icc_cshrc_e
 echo "Deployment ready."
 #
 # $Log: not supported by cvs2svn $
+# Revision 1.1  2006/06/07 11:10:57  cjm
+# Initial revision
+#
 #
